### ISSUE TITLE
Testflight app no longer working

### ISSUE THREAD

**Issue by mroberts1** [pitr/gemini-ios#8]
I've been using this client daily and finding it very useful, but now I'm getting a message that the Beta has expired and it doesn't work anymore. What's happening to the app now and how can i get it back?

**Comment by pitr** [comment]
Hi @mroberts1. Glad to hear that the app is useful to you. The latest version in Testflight (2020.11) should be good until March, please try updating it in the Testflight.

In the meantime, I have been trying to submit it to the app store so that one wouldn't need to bother with expiring Testflight versions. First attempt has been declined, in part due to the use of the word "browser" which for many people suggests web/http browser, and App Store reviewers want to make sure this is clear. I am trying to submit it again.

**Comment by pitr** [comment]
my mistake, looks like I forgot to activate the newest build in Testflight. It is active now

**Comment by pitr** [comment]
And serendipitously the app was approved!!!

https://apps.apple.com/de/app/the-gemini-browser/id1514950389?l=en
